### ISSUE TITLE
Warning and error on `hash` print

### ISSUE THREAD

**Issue by ckormanyos** [0vm/Simple-HWID-Checker#1]
Hi Ken (@0vm)

When compiling your simple hardware checker on MSVC 14.2, I received an error on the print of the `hash` and a separate warning when converting 16-bit characters to 8-bit characters in `std::string`.

This PR corrects the error and warning.

But I'm not exactly sure if the value of the `hash` is actually supposed to be a scalar integral value or a string. So maybe check this?

I will submit a PR for these proposed changes.

**Comment by ckormanyos** [comment]
See also #2

**Comment by ckormanyos** [comment]
Thanks Ken (@0vm) for this PR handling and for making this nice project. Closed by #2

**Comment by 0vmm** [comment]
For some reason I cannot comment, But I only checked using 143 not 142, sorry about that. Just tested this, great work, thank you!

**Comment by 0vmm** [comment]
![image](https://github.com/0vm/Simple-HWID-Checker/assets/142158250/183f31c6-adfc-449b-b502-277d65e238d4)

**Comment by 0vmm** [comment]
The hash is not meant to be a string, but might aswell keep it, makes no difference.

**Comment by ckormanyos** [comment]
Thanks Ken I'm still not sure about the best way to represent the `hash`. Actually your comment just overlapped mine. So one thing mine odes is extend the width of the hash to 32-bit. Yours was previously 16-bit.

I guess this probably does not matter?

**Comment by 0vm** [comment]
Does not matter. I'll update this in the future to get more identifiers and i'll fix it up!

**Comment by ckormanyos** [comment]
> Does not matter. I'll update this in the future to get more identifiers and i'll fix it up!

Got it. Thank you.
This is a nice project. Thanks for supporting it.
